'''
You are given two strings s and t.

String t is generated by random shuffling string s and then add one more letter at a random position.

Return the letter that was added to t.


'''

from typing import Counter


class Solution:
    def findTheDifference(self, s: str, t: str) -> str:
        mappa=Counter(s)

        for i in t:
            if i not in mappa:
                return i
            else:
                mappa[i]-=1
                if mappa[i]<0:
                    return i
        